version: '3'
services:
  java-srv:
    build:
      context: java-srv
    ports:
      - 80:8080
    depends_on:
      - db
    links:
      - "db:db"

  db:
    container_name: db
    image: solr:8.2
    ports:
     - 8981:8983
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  db2:
    image: solr:8.2
    container_name: db2
    ports:
     - 8982:8983
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  db3:
    image: solr:8.2
    container_name: db3
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    ports:
      - 8983:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  create-collection:
    image: solr:8.2
    container_name: create-collection
    environment:
      - SOLR_HOST=db
    command:
      - bash
      - "-e"
      - "-x"
      - "-c"
      - "wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://$$SOLR_HOST:8983/; solr create_collection -c dog -p 8983"

  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zoo/zoo1/data:/data
      - ./zoo/zoo1/datalog:/datalog

  zoo2:
    image: zookeeper:3.5
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zoo/zoo2/data:/data
      - ./zoo/zoo2/datalog:/datalog

  zoo3:
    image: zookeeper:3.5
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./zoo/zoo3/data:/data
      - ./zoo/zoo3/datalog:/datalog
